# export UID=`id -u`; export GID=`id -g`; docker-compose up -d

version: "3.3"

services:

  dev:
    build:
      context: .
      dockerfile: Dockerfile2
    tty: True
    user: $UID:$GID:$USER
    volumes:
      - ./wrfout_to_cf:/tmp/wrfout_to_cf
      - $HOME/scratch/chch:/tmp/chch